version: "2"
services:
  database:
    image: "postgres"
    container_name: "postgres-pedidos"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    networks:
      - salud-pedidos

networks:
  salud-pedidos:
    driver: bridge